### ISSUE TITLE
Package does not work in IE8

### ISSUE THREAD

**Issue by guybedford** [RubenVerborgh/promiscuous#22]
I was doing some IE8 testing today, and had an error with this promise implementation.

The error was on this line - https://github.com/ModuleLoader/es6-module-loader/blob/master/lib/promise.js#L36

where `queue` was undefined.

If you happen to have time at some point to play around with the compatibility, it would be a great help in getting IE8 support for the ES6 module loader.

No pressure at all though!

**Comment by RubenVerborgh** [comment]
Closing this as IE8 is probably no longer an issue today.
