### ISSUE TITLE
how to break promise chain?

### ISSUE THREAD

**Issue by nothinggift** [RubenVerborgh/promiscuous#31]
is it possible?

**Comment by RubenVerborgh** [comment]
I'm not sure what exactly you mean, but you can throw an exception from a promise handler.

**Comment by nothinggift** [comment]
sorry about that,i'm not good at English.
I have a promise chain like the following:
`stepOne().then(stepTwo,errorHandleOne).then(stepThree,errorHandleTwo)`

In the errorHandleOne, can i break the chain so that both the `stepThree` and `errorHandleTwo` would not be called?

I tried throw exception ,it was jut like reject.

**Comment by RubenVerborgh** [comment]
Just not resolving (nor rejecting) the promise in `stepOne` will break the chain.

**Comment by nothinggift** [comment]
`errorHandleOne`  need be called, so i make a function:
`function breakPromiseChain(){
    return new Promise(){};
}`
It`s worked.
thanks for replying.

**Comment by RubenVerborgh** [comment]
In that case, returning an unresolved promise is indeed the way.
