### ISSUE TITLE
Add option to warn on unhandled exceptions

### ISSUE THREAD

**Issue by creationix** [RubenVerborgh/promiscuous#32]
It would be neat if there was an option to handle unhandled exceptions/rejections globally.  Then as an app author, I could log the error or crash my server.

Note that node.js intends to crash on unhandled rejections in the next major release against the spec.

If you don't want to add such an option, can you at least help he find the place in the code where I could handle it myself in a customized version of this library?

**Comment by RubenVerborgh** [comment]
Thanks for raising this issue.

I created promiscuous at a time when small Promise implementations were still scarce; however, there are many alternatives now, many built-in, and they have such options. So my first recommendation would be to look for another Promise library if you need more complicated functionality; promiscuous was designed primarily for size.

However, if you want to make the edit, you will need to add an `if` statement [here](https://github.com/RubenVerborgh/promiscuous/blob/v0.6.0/promiscuous.js#L54) to handle the case when no callbacks are queued as follows:

```JavaScript
if (rejected && !queue.length)
    globalErrorHandler(value || new Error('Unhandled promise rejection.'));
```

**Comment by creationix** [comment]
Thanks!
