### ISSUE TITLE
NPM Version That Supports setTimeout and Doesn't Pollute Window Object

### ISSUE THREAD

**Issue by Nicholas-Westby** [RubenVerborgh/promiscuous#38]
I've installed this with NPM and am requiring it like so:

```javascript
// Add Promise support (for IE11).
if (typeof Promise === "undefined") {
    require("promiscuous/promiscuous-browser-full");
}
```

I needed to use the "-browser-full" version in order to avoid `setImmediate` (i.e., it uses setTimeout instead), since it's not supported on Chrome.

However, the "-browser-full" version also sets the `window.Promise` object directly, and the tool I'm trying to make is supposed to be entirely self-contained. That is, I'd prefer if I could do this instead:

```javascript
// Add Promise support (for IE11).
var Promise = require("promiscuous/promiscuous-some-different-variation");
```

Meaning, the "-some-different-variation" version would be using `module.exports` rather than `window.Promise`.

Is this something you would consider? I'd be happy to contribute a pull request.

**Comment by RubenVerborgh** [comment]
Sure, let's make a `-browser-shim` version?

**Comment by Nicholas-Westby** [comment]
Will do! I'll try to find some time to work on this soon (next week or two).

**Comment by Nicholas-Westby** [comment]
I created the pull request. FYI, I'm not sure if there's anything additional I need to do to ensure this is included with the NPM module, but in the very least the file is generated by the `build.js` file.

I called it `promiscuous-browser-shim-full.js` since it's an unminified version.

I'm happy to update the pull request if you'd like me to change anything.

**Comment by RubenVerborgh** [comment]
Thanks, following up in #39.
