### ISSUE TITLE
How to add a ES2018 Promise#finally method?

### ISSUE THREAD

**Issue by Nikaple** [RubenVerborgh/promiscuous#43]
Usually I would use this one:
```javascript
Promise.prototype.finally = function(callback) {
        const constructor = this.constructor;

        return this.then(
            value => constructor.resolve(callback()).then(() => value),
            reason => constructor.resolve(callback()).then(() => { throw reason; })
        );
    };
```
But it failed with `promiscuous` as it doesn't use prototype.

**Comment by RubenVerborgh** [comment]
Yeah… the main goal of this library is size, not functionality. You'd have to add this to the core.

I think many better options exist in 2018 with transpilation etc.
I will update the README.

Note: I think the parentheses after callback (twice) are wrong.
